name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install libboost-dev libz-dev
    - name: make
      run: make
    - name: make check
      run: make check
